from confirmed_email.tests.models_tests import QueuedEmailMessageTests
from confirmed_email.tests.models_tests import AddressConfirmationTests
from confirmed_email.tests.sender_tests import ConfirmedEmailMessageTests
