from confirmed_email.tests.test_models import QueuedEmailMessageTests
from confirmed_email.tests.test_models import AddressConfirmationTests
from confirmed_email.tests.test_sender import ConfirmedEmailMessageTests
